version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - document-processor

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/ddialog
    depends_on:
      - db

  document-processor:
    build:
      context: ./document-processor
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ddialog
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: