FROM python:3.9

# Set up the working directory
WORKDIR /app

# Install Poetry and netcat
RUN pip install poetry && apt-get update && apt-get install -y netcat-openbsd

# Copy only the pyproject.toml file
COPY pyproject.toml /app/

# Generate a new poetry.lock file
RUN poetry lock

# Install project dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Copy the rest of the application code
COPY . /app

# Make the entrypoint script executable and ensure it has the correct line endings
RUN chmod +x /app/entrypoint.sh && \
    sed -i 's/\r$//' /app/entrypoint.sh

# Expose the port for the application
EXPOSE 8000

# Use the entrypoint script
CMD ["/bin/sh", "/app/entrypoint.sh"]