FROM python:3.9

# Configura o diretório de trabalho
WORKDIR /app

# Instala o Poetry
RUN pip install poetry

# Copia o arquivo de configuração do Poetry e o lockfile
COPY pyproject.toml poetry.lock* /app/

# Configura o Poetry para não criar um ambiente virtual
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Copia o arquivo .env para o contêiner
COPY .env /app/.env

# Sincroniza o poetry.lock com pyproject.toml para evitar erros de versão
RUN poetry lock --no-update

# Carrega as variáveis de ambiente do .env e instala as dependências
RUN export $(cat /app/.env | xargs) && poetry install --no-interaction --no-ansi

# Copia o restante do código para o container
COPY . /app

# Remove the following line:
# RUN poetry add pytest

# Expõe a porta para a aplicação
EXPOSE 8000

# Comando padrão para iniciar a aplicação
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]